from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        Dialog.setWindowTitle("Youtube Download")
        Dialog.setWindowIcon(QtGui.QIcon("images/yt.jfif"))
        self.urlLabel = QtWidgets.QLabel(Dialog)
        self.urlLabel.setGeometry(QtCore.QRect(40, 40, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.urlLabel.setFont(font)
        self.urlLabel.setObjectName("urlLabel")
        self.urlTextField = QtWidgets.QLineEdit(Dialog)
        self.urlTextField.setGeometry(QtCore.QRect(40, 90, 400, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.urlTextField.setFont(font)
        self.urlTextField.setText("")
        self.urlTextField.setObjectName("urlTextField")
        self.downloadButton = QtWidgets.QPushButton(Dialog)
        self.downloadButton.setGeometry(QtCore.QRect(160, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.downloadButton.setFont(font)
        self.downloadButton.setObjectName("downloadButton")
        self.exampleLabel = QtWidgets.QLabel(Dialog)
        self.exampleLabel.setEnabled(False)
        self.exampleLabel.setGeometry(QtCore.QRect(40, 200, 430, 21))
        self.exampleLabel.setStyleSheet("")
        self.exampleLabel.setText("Example:   https://www.youtube.com/watch?v=ZYzbalQ6Lg8")
        self.exampleLabel.setObjectName("exampleLabel")
        self.downloadSuccessLabel = QtWidgets.QLabel(Dialog)
        self.downloadSuccessLabel.setGeometry(QtCore.QRect(160, 280, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.downloadSuccessLabel.setFont(font)
        self.downloadSuccessLabel.setObjectName("downloadSuccessLabel")
        self.downloadedIconLabel = QtWidgets.QLabel(Dialog)
        self.downloadedIconLabel.setEnabled(True)
        self.downloadedIconLabel.setGeometry(QtCore.QRect(80, 280, 51, 41))
        self.downloadedIconLabel.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.downloadedIconLabel.setText("")
        self.downloadedIconLabel.setPixmap(QtGui.QPixmap("images/downloadsuccess.png"))
        self.downloadedIconLabel.setScaledContents(True)
        self.downloadedIconLabel.setObjectName("downloadedIconLabel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 20, 120, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/youtubelogo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.downloadedIconLabel.hide()
        self.downloadSuccessLabel.hide()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Youtube Download"))
        self.urlLabel.setText(_translate("Dialog", "Enter URL:"))
        self.downloadButton.setText(_translate("Dialog", "Download !!"))
        self.downloadSuccessLabel.setText(_translate("Dialog", "Download Success !"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
